version: '3'
services:
  juggernaut:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: python ./test_askar.py

  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: development
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 5
